name: Foodies
description: Always know where to eat!

version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: any
  flutter_dotenv: any
  google_fonts: any
  http: any
  shared_preferences: any
  flutter_map: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
